# Argo CD Ingress
rules:
  - host: homelab.taild3b4b8.ts.net
    http:
      paths:
        - path: /argo
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                number: 80
---
# Vault Ingress
rules:
  - host: homelab.taild3b4b8.ts.net
    http:
      paths:
        - path: /vault
          pathType: Prefix
          backend:
            service:
              name: vault
              port:
                number: 8200